services:
  www:
    container_name: web
    image: ikondesign/webprod
    ports: 
        - "8001:80"
    networks:
        - default
    links:
        - db
    environment:
        - ENVARIABLE=prod
  db:
    container_name: db
    image: mysql
    ports: 
        - "3306:3306"
    environment:
        MYSQL_DATABASE: videgrenierenligne
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
    volumes:
        - ./www/vide-grenier-en-ligne-master/sql:/docker-entrypoint-initdb.d
       # - ./persistent:/var/lib/mysql
    networks:
        - default
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links: 
        - db:db
    ports:
        - 8000:80
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
