services:
  www:
    container_name: web
    #build: .
    image: ikondesign/webpreprod
    ports: 
        - "8001:80"
    #volumes:
    #    - C:\Users\ProAl\OneDrive\Bureau\test\cube5\www\vide-grenier-en-ligne-master:/var/www/html/
    networks:
        - default
    links:
        - db
    environment:
        - ENVARIABLE=preprod
  db:
    container_name: db
    image: mysql
    ports: 
        - "3306:3306"
    environment:
        MYSQL_DATABASE: videgrenierenligne
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
    volumes:
        - /Users/clement/Desktop/cube-preprod/cube5/www/vide-grenier-en-ligne-master/sql:/docker-entrypoint-initdb.d
       # - ./persistent:/var/lib/mysql
    networks:
        - default
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links: 
        - db:db
    ports:
        - 8000:80
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
