services:
  www:
    build: .
    ports: 
        - "8001:80"
    volumes:
        - /Users/clement/Desktop/cube5good/cube5/www/vide-grenier-en-ligne-master/public:/var/www/html/
    links:
        - db
    networks:
        - default
  db:
    image: mysql
    ports: 
        - "3306:3306"
    environment:
        MYSQL_DATABASE: cube5
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
    volumes:
        - /Users/clement/Desktop/cube5good/cube5/www/vide-grenier-en-ligne-master/sql:/docker-entrypoint-initdb.d
       # - persistent:/var/lib/mysql
    networks:
        - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - db:db
    ports:
        - 8000:80
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
#  php:
#    container_name: php
#    image: php:7.2-fpm
#    volumes:
#      - web:/script:ro
#  database:
#    container_name: database
#    image: mariadb:latest
#    volumes:
#      - database:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=videgrenier
#      - MYSQL_USER=test
#      - MYSQL_PASSWORD=test
#
#volumes:
#  web:
#    driver: local
#    driver_opts:
#      device: ./www
#      o: bind
#      type: none
#  nginxconf:
#    driver: local
#    driver_opts:
#      device: ./nginx
#      o: bind
#      type: none
#  php:
#    driver: local
#    driver_opts:
#      device: ./php
#      o: bind
#      type: none
#  database:
#    driver: local
#    driver_opts:
#      device: ./database
#      o: bind
#      type: none